set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR m68k)

if("${CONFIG}" STREQUAL "")
    set(CONFIG "aos68k")
endif()


set(CMAKE_C_COMPILER vc)
set(CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> +${CONFIG} <SOURCE> <DEFINES> <INCLUDES> <FLAGS> -c99 -c -o <OBJECT>")


set(CMAKE_ASM_COMPILER vc)
set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> +${CONFIG} <SOURCE> <DEFINES> <INCLUDES> <FLAGS> -c -o <OBJECT>")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_ASM_COMPILER>  +${CONFIG} <OBJECTS>")


set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_C_COMPILER>  +${CONFIG} <OBJECTS> -o ${PROJECT_NAME}")
set(CMAKE_ASM_LINK_EXECUTABLE ${CMAKE_C_LINK_EXECUTABLE})
